# Site settings
title: Yuliana Herrera
email: yulianaherreraalcantara@gmail.com
url: https://yherrera1906.github.io/cybersecurity-portfolio
description: "Portfolio of cybersecurity work samples for a junior-level cyber security professional."
keywords: "cybersecurity, cyber, security, portfolio, tech"
skills: "Cybersecurity - Analyst - Ethical Hacker"
meta_author: Yuliana Herrera

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
#Â - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: 

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 111827 
  primary-rgb: "17,24,39"
  secondary: 14B8A6
  secondary-dark: 0F766E

# Footer settings
footer:
  copyright: Yuliana Herrera
  location: Location
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: www.linkedin.com/in/yuliana-herrera-68ab24343
  - title: github
    url: https://github.com/yherrera1906

# Email Address (make sure to include "mailto:" before your email!)
email:
  email-url: mailto:yulianaherreraalcantara@gmail.com

# Postal address (add as many lines as necessary)
location:
  - line: Fort Lee, New Jersey

# Credits content
credits: 'Freelancer is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.
Cyber icons created by <a href="https://www.flaticon.com/free-icons/cyber-attack" title="cyber attack icons">Freepik - Flaticon</a>.'

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
